version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      # - "./html/:/var/www/html/"
      - ./ini/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "80:80" 